/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'alarmOffset' : IDL.Opt(IDL.Nat),
  'alarmEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Bool, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'updateAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Bool, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'alarmOffset' : IDL.Opt(IDL.Nat),
    'alarmEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'createAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Bool, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'updateAppointment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Nat,
          IDL.Bool,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };